name: CI/CD InspiraImage

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      BACKEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/inspiraimageapi:latest
      FRONTEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/inspiraimageui:latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      # 🧱 Backend
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Backend
        working-directory: ./inspiraimageapi
        run: mvn clean package -DskipTests

      # 🎨 Frontend
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Frontend
        working-directory: ./inspiraimageui
        run: |
          npm install
          npm run build

      # 🐳 Login Docker Hub
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 🐳 Build + Push Backend
      - name: Build Backend Image
        run: docker build -t $BACKEND_IMAGE ./inspiraimageapi

      - name: Push Backend Image
        run: docker push $BACKEND_IMAGE

      # 🐳 Build + Push Frontend
      - name: Build Frontend Image
        run: docker build -t $FRONTEND_IMAGE ./inspiraimageui

      - name: Push Frontend Image
        run: docker push $FRONTEND_IMAGE
