name: CI/CD InspiraImage

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.sha }}
      BACKEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/inspiraimageapi
      FRONTEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/inspiraimageui

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 🧱 Backend
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Backend
        working-directory: ./inspiraimageapi
        run: mvn clean package -DskipTests

      # 🎨 Frontend
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Frontend (com API correta)
        working-directory: ./inspiraimageui
        run: |
          NEXT_PUBLIC_API_URL=http://inspiraimageapi-service:8080 npm ci
          NEXT_PUBLIC_API_URL=http://inspiraimageapi-service:8080 npm run build

      # 🐳 Login Docker Hub
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 🚀 Backend Image
      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./inspiraimageapi
          push: true
          tags: |
            ${{ env.BACKEND_IMAGE }}:latest
            ${{ env.BACKEND_IMAGE }}:${{ env.IMAGE_TAG }}

      # 🚀 Frontend Image
      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./inspiraimageui
          push: true
          tags: |
            ${{ env.FRONTEND_IMAGE }}:latest
            ${{ env.FRONTEND_IMAGE }}:${{ env.IMAGE_TAG }}